### ISSUE TITLE
question about use of reactivemongo

### ISSUE THREAD

**Issue by klaeufer** [sshilpika/metrics-dashboard-storage-service#5]
In this storage service, are we using it only its BSON support but not the actual reactive driver?

**Comment by klaeufer** [comment]
OK, I'm now seeing the reactive driver being used here:

https://github.com/sshilpika/metrics-dashboard-storage-service/blob/master/src/main/scala/package.scala#L24

Nevertheless, I don't follow why we are using the reactive driver at all in this batch process. The more I look at it, the more I think the logic would become simpler by using the blocking driver. 

https://github.com/sshilpika/metrics-dashboard-storage-service/blob/master/src/main/scala/service/Boot.scala#L28

**Comment by sshilpika** [comment]
I was just experimenting with BSON,
we can have either casbah or reactive.

With warm regards,
Shilpika

----- Reply message -----
